using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApi.Models.Build
{
    // Generated by https://quicktype.io

    public class BuildCompleted
    {
        public string SubscriptionId { get; set; }
        public long NotificationId { get; set; }
        public string Id { get; set; }
        public string EventType { get; set; }
        public string PublisherId { get; set; }
        public Essage Message { get; set; }
        public Essage DetailedMessage { get; set; }
        public Resource Resource { get; set; }
        public string ResourceVersion { get; set; }
        public ResourceContainers ResourceContainers { get; set; }
        public System.DateTimeOffset CreatedDate { get; set; }
    }

    public class Essage
    {
        public string Markdown { get; set; }
    }

    public class Resource
    {
        public ResourceLinks Links { get; set; }
        public DefinitionLinks Properties { get; set; }
        public object[] Tags { get; set; }
        public object[] ValidationResults { get; set; }
        public Lan[] Plans { get; set; }
        public DefinitionLinks TriggerInfo { get; set; }
        public long Id { get; set; }
        public string BuildNumber { get; set; }
        public string Status { get; set; }
        public string Result { get; set; }
        public System.DateTimeOffset QueueTime { get; set; }
        public System.DateTimeOffset StartTime { get; set; }
        public System.DateTimeOffset FinishTime { get; set; }
        public string Url { get; set; }
        public Definition Definition { get; set; }
        public Project Project { get; set; }
        public string Uri { get; set; }
        public string SourceBranch { get; set; }
        public string SourceVersion { get; set; }
        public Queue Queue { get; set; }
        public string Priority { get; set; }
        public string Reason { get; set; }
        public LastChangedBy RequestedFor { get; set; }
        public LastChangedBy RequestedBy { get; set; }
        public System.DateTimeOffset LastChangedDate { get; set; }
        public LastChangedBy LastChangedBy { get; set; }
        public string Parameters { get; set; }
        public Lan OrchestrationPlan { get; set; }
        public Logs Logs { get; set; }
        public Repository Repository { get; set; }
        public bool KeepForever { get; set; }
        public bool RetainedByRelease { get; set; }
    }

    public class Definition
    {
        public DefinitionLinks Links { get; set; }
        public long Id { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public string Path { get; set; }
        public string Type { get; set; }
        public string QueueStatus { get; set; }
        public long Revision { get; set; }
        public Project Project { get; set; }
    }

    public class DefinitionLinks
    {
    }

    public class Project
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Url { get; set; }
        public string State { get; set; }
        public long Revision { get; set; }
        public string Visibility { get; set; }
    }

    public class LastChangedBy
    {
        public string Id { get; set; }
        public string DisplayName { get; set; }
        public string UniqueName { get; set; }
        public string Url { get; set; }
        public string ImageUrl { get; set; }
    }

    public class ResourceLinks
    {
        public Self Self { get; set; }
        public Self Web { get; set; }
        public Self Timeline { get; set; }
    }

    public class Self
    {
        public string Href { get; set; }
    }

    public class Logs
    {
        public long Id { get; set; }
        public string Type { get; set; }
        public string Url { get; set; }
    }

    public class Lan
    {
        public string PlanId { get; set; }
    }

    public class Queue
    {
        public DefinitionLinks Links { get; set; }
        public long Id { get; set; }
        public string Name { get; set; }
        public Pool Pool { get; set; }
    }

    public class Pool
    {
        public long Id { get; set; }
        public string Name { get; set; }
    }

    public class Repository
    {
        public string Id { get; set; }
        public string Type { get; set; }
        public object Clean { get; set; }
        public bool CheckoutSubmodules { get; set; }
    }

    public class ResourceContainers
    {
        public Collection Collection { get; set; }
        public Collection Server { get; set; }
        public Collection Project { get; set; }
    }

    public class Collection
    {
        public string Id { get; set; }
        public string BaseUrl { get; set; }
    }


}
