namespace WebApi.Models.WorkUpdated
{

    // Generated by https://quicktype.io

    public class WorkUpdated
    {
        public string SubscriptionId { get; set; }
        public long NotificationId { get; set; }
        public string Id { get; set; }
        public string EventType { get; set; }
        public string PublisherId { get; set; }
        public Essage Message { get; set; }
        public Essage DetailedMessage { get; set; }
        public Resource Resource { get; set; }
        public string ResourceVersion { get; set; }
        public ResourceContainers ResourceContainers { get; set; }
        public System.DateTimeOffset CreatedDate { get; set; }
    }

    public class Essage
    {
        public string Markdown { get; set; }
    }

    public class Resource
    {
        public long Id { get; set; }
        public long WorkItemId { get; set; }
        public long Rev { get; set; }
        public RevisedBy RevisedBy { get; set; }
        public System.DateTimeOffset RevisedDate { get; set; }
        public ResourceFields Fields { get; set; }
        public ResourceLinks Links { get; set; }
        public string Url { get; set; }
        public Revision Revision { get; set; }
    }

    public class ResourceFields
    {
        public FieldsSystemRev SystemRev { get; set; }
        public SystemEdDate SystemAuthorizedDate { get; set; }
        public SystemEdDate SystemRevisedDate { get; set; }
        public SystemEdDate SystemChangedDate { get; set; }
        public FieldsSystemRev SystemWatermark { get; set; }
        public SystemHistory SystemHistory { get; set; }
    }

    public class SystemEdDate
    {
        public System.DateTimeOffset OldValue { get; set; }
        public System.DateTimeOffset NewValue { get; set; }
    }

    public class SystemHistory
    {
        public string OldValue { get; set; }
        public string NewValue { get; set; }
    }

    public class FieldsSystemRev
    {
        public long OldValue { get; set; }
        public long NewValue { get; set; }
    }

    public class ResourceLinks
    {
        public Html Self { get; set; }
        public Html WorkItemUpdates { get; set; }
        public Html Parent { get; set; }
        public Html Html { get; set; }
    }

    public class Html
    {
        public string Href { get; set; }
    }

    public class RevisedBy
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public string UniqueName { get; set; }
        public string Url { get; set; }
        public string ImageUrl { get; set; }
    }

    public class Revision
    {
        public long Id { get; set; }
        public long Rev { get; set; }
        public RevisionFields Fields { get; set; }
        public Relation[] Relations { get; set; }
        public RevisionLinks Links { get; set; }
        public string Url { get; set; }
    }

    public class RevisionFields
    {
        public string SystemAreaPath { get; set; }
        public string SystemTeamProject { get; set; }
        public string SystemIterationPath { get; set; }
        public string SystemWorkItemType { get; set; }
        public string SystemState { get; set; }
        public string SystemReason { get; set; }
        public string SystemAssignedTo { get; set; }
        public System.DateTimeOffset SystemCreatedDate { get; set; }
        public string SystemCreatedBy { get; set; }
        public System.DateTimeOffset SystemChangedDate { get; set; }
        public string SystemChangedBy { get; set; }
        public string SystemTitle { get; set; }
        public double MicrosoftVstsSchedulingRemainingWork { get; set; }
        public double MicrosoftVstsSchedulingOriginalEstimate { get; set; }
        public double MicrosoftVstsSchedulingCompletedWork { get; set; }
        public string MicrosoftVstsCommonActivity { get; set; }
        public System.DateTimeOffset MicrosoftVstsCommonStateChangeDate { get; set; }
        public System.DateTimeOffset MicrosoftVstsCommonActivatedDate { get; set; }
        public string MicrosoftVstsCommonActivatedBy { get; set; }
        public long MicrosoftVstsCommonPriority { get; set; }
        public double MicrosoftVstsCommonStackRank { get; set; }
        public string SystemDescription { get; set; }
        public string SystemHistory { get; set; }
    }

    public class RevisionLinks
    {
        public Html Self { get; set; }
        public Html WorkItemRevisions { get; set; }
        public Html Parent { get; set; }
    }

    public class Relation
    {
        public string Rel { get; set; }
        public string Url { get; set; }
        public Attributes Attributes { get; set; }
    }

    public class Attributes
    {
        public bool IsLocked { get; set; }
    }

    public class ResourceContainers
    {
        public Collection Collection { get; set; }
        public Collection Server { get; set; }
        public Collection Project { get; set; }
    }

    public class Collection
    {
        public string Id { get; set; }
        public string BaseUrl { get; set; }
    }



}
